### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by hammer-x86-64** [ashn-dot-dev/sunder#121]
Well here they are:
* How usable is sunder?
* How stable is it?

_ps: i really like sunder_

**Comment by ashn-dot-dev** [comment]
Howdy @hammer-x86-64 👋. To answer your questions...

> How usable is sunder?

I think that depends on the definition of "usable" in this context. For reference, I have been using Sunder extensively this past year for some recreational programming problems and miscellaneous side projects (some of which you can find in my [scratch code repository](https://github.com/ashn-dot-dev/scratch) or my [SundOS barebones x86-64 kernel](https://github.com/ashn-dot-dev/sundos)). Sunder is completely usable for something like Advent of Code, and I would consider it pretty suitable for writing small command line tools (a mini `grep` clone would definitely be possible in Sunder). But it is important to keep in mind that Sunder is currently limited in certain areas (C FFI and math-oriented areas in particular), so I wouldn't necessarily consider it usable for something like game engine development where one would need to work with floating point numbers or talk to a library like SDL2.

> How stable is it?

Sunder is a mostly-for-fun project that I work on in my free time, and the project doesn't adhere to semantic version or any other strong compatibility guarantee, so I can't promise complete future stability (i.e. the code you write today will work in five years without changes). That being said, at this point I consider Sunder to be [sufficiently stable](https://www.ashn.dev/blog/2022-07-14-sunder-is-a-sufficiently-stable-programming-language.html), and in particular I plan on using today's [2022.02.19 release](https://github.com/ashn-dot-dev/sunder/releases/tag/2023.02.19) for a bunch of upcoming blog posts, so I am confident in saying that code written using this release *should* be relatively stable moving forward. I *do* plan on eventually making additions to the language (e.g. Rust-style `enum`s, C-style `unions`, and language / standard library support for things like `f32` and `f64` types), but those additions should not break existing code if I am doing my job as a compiler author right.

Sunder is *my* favorite programming language, but I don't want to pretend that is at the same caliber as languages such as [Rust](https://github.com/rust-lang) or [Zig](https://github.com/ziglang/zig), so I would encourage you to try Sunder out for yourself and see if it is suitable for *your* needs in particular. And of course if you have any other questions or feedback then I would love to hear it. 😊

**Comment by ashn-dot-dev** [comment]
Update to this issue. Sunder [version 2023.08.01](https://github.com/ashn-dot-dev/sunder/releases/tag/2023.08.01) has gained support for C FFI (although you will need to generate bindings yourself), floating point types, union types, and a bunch of other neat stuff. Additionally, the 2023.08.01 release is intended to be the next long-term language release (I really don't have much more I would even want to add at this point), so I would say that Sunder is definitely stable enough to use on a small to medium sized project. Although my comments on Sunder being a mostly-for-fun project still hold true, I would feel much more confident recommending Sunder for a project today!

I am going to close this issue since it has not had activity for a while, but feel free to comment if you have further questions.
